name: 'cloud_storage'
host: '127.0.0.1'
port: 8080
file_location: '\usr\share\nginx\html\upload'
ceph_access_key: 'A6Z3CBUNMW5CAA21Q8XO'
ceph_secret_key: 'iNbTzedbYMPc1ACxIhZvnAUubUGZCskUrnGCvOgd'
ceph_gateway_endpoint: 'http://172.20.0.15:7480'